### PR TITLE
[#18] add class Invoker\ParameterResolver\CallbackResolver

### PR DESCRIPTION
**Pull request by kaluzki**
This class implements the "middleware" approach:
- already resolved parameters are NOT PASSED to the callback
- the result of the callback is MERGED INTO the array of resolved parameters

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you for the PR. I'm not sure I understand the goal of this class? How/when is it useful?

**Comment by kaluzki** [comment]
Originally, I needed a resolver that could resolve the [variadic](https://php.net/manual/functions.arguments.php#functions.variable-arg-list) argument (#19).
When I took a closer look at the previous resolver implementations,
I noticed that not only are they all similar in structure,
but sometimes also have absolutely identical code. 
So this class is nothing else than outsourcing of common code passages.

The procedure in each previous implementation is always the same:

1. Skip parameters already resolved (**common**)
2. Iterate over unresolved parameters and solve them if necessary with a given strategy (individual)
3. Add currently resolved parameters to the previous result (**common**)

```php

/** @var \Psr\Container\ContainerInterface $container */
$container = null;

$callbacks = [
        
    AssociativeArrayResolver::class => function (
        array $provided, 
        ReflectionParameter ...$parameters
    ) {
        $resolved = [];
        foreach ($parameters as $index => $parameter) {
            if (array_key_exists($parameter->name, $provided)) {
                $resolved[$index] = $provided[$parameter->name];
            }
        }

        return $resolved;
    },

    NumericArrayResolver::class     => function (
        array $provided, 
        ReflectionParameter ...$parameters
    ) {
        $resolved = [];
        foreach (array_keys($parameters) as $index) {
            if (array_key_exists($index, $provided)) {
                $resolved[$index] = $provided[$index];
            }
        }

        return $resolved;
    },

    TypeHintResolver::class         => function (
        array $provided, 
        ReflectionParameter ...$parameters
    ) {
        $resolved = [];
        foreach ($parameters as $index => $parameter) {
            if (($class = $parameter->getClass()) && array_key_exists($class->name, $provided)) {
                $resolved[$index] = $provided[$class->name];
            }
        }

        return $resolved;
    },

    DefaultValueResolver::class => function (
        array $provided, 
        ReflectionParameter ...$parameters
    ) {
        $resolved = [];
        foreach ($parameters as $index => $parameter) {
            if ($parameter->isOptional()) {
                try {
                    $resolved[$index] = $parameter->getDefaultValue();
                } catch (\ReflectionException $e) {
                    // Can't get default values from PHP internal classes and functions
                }
            }
        }

        return $resolved;
    },
    
    TypeHintContainerResolver::class => function (
        array $provided, 
        ReflectionParameter ...$parameters
    ) use ($container) {
        $resolved = [];
        foreach ($parameters as $index => $parameter) {
            if (($class = $parameter->getClass()) && $container->has($class->name)) {
                $resolved[$index] = $container->get($class->name);
            }
        }

        return $resolved;
    },
    
    ParameterNameContainerResolver::class => function (
        array $provided,
        ReflectionParameter ...$parameters
    ) use ($container) {
        $resolved = [];
        foreach ($parameters as $index => $parameter) {
            if (($name = $parameter->name) && $container->has($name)) {
                $resolved[$index] = $container->get($name);
            }
        }

        return $resolved;
    },
    
];

$chain = new ResolverChain(array_map(function(callable $callback) {
    return new CallbackResolver($callback);
}, $callbacks));
```

**Comment by kaluzki** [comment]
After the last comment, I realized that the actual iteration can also be rationalized.
With the help of [generators](https://php.net/manual/language.generators.overview.php) one can reduce the individual part to a few lines of code:

```php

namespace Invoker\ParameterResolver;

use ReflectionFunctionAbstract;
use ReflectionParameter;

/**
 */
class GeneratorResolver implements ParameterResolver
{
    /**
     * @var callable
     */
    private $generator;

    /**
     * @param callable $generator function(ReflectionParameter $parameter, array $provided = []): array
     */
    public function __construct(callable $generator)
    {
        $this->generator = $generator;
    }

    /**
     * @inheritdoc
     */
    public function getParameters(
        ReflectionFunctionAbstract $reflection,
        array $providedParameters,
        array $resolvedParameters
    ) {
        $parameters = $reflection->getParameters();
        // Skip parameters already resolved
        if (!empty($resolvedParameters)) {
            $parameters = array_diff_key($parameters, $resolvedParameters);
        }

        $resolvedByGenerator = [];
        foreach ($parameters as $index => $parameter) {
            foreach (call_user_func($this->generator, $parameter, $providedParameters) as $value) {
                $resolvedByGenerator[$index] = $value;
            }
        }

        return $resolvedParameters + $resolvedByGenerator;
    }
}

/** @var \Psr\Container\ContainerInterface $container */
$container = null;

$generators = [
        
    AssociativeArrayResolver::class       => function (
        ReflectionParameter $parameter, 
        array $provided
    ) {
        if (array_key_exists($parameter->name, $provided)) {
            yield $provided[$parameter->name];
        }
    },
    
    NumericArrayResolver::class           => function (
        ReflectionParameter $parameter, 
        array $provided
    ) {
        if (array_key_exists($parameter->getPosition(), $provided)) {
            yield $provided[$parameter->getPosition()];
        }
    },
    
    TypeHintResolver::class               => function (
        ReflectionParameter $parameter, 
        array $provided
    ) {
        if (($class = $parameter->getClass()) && array_key_exists($class->name, $provided)) {
            yield $provided[$class->name];
        }
    },
    
    DefaultValueResolver::class           => function (
        ReflectionParameter $parameter
    ) {
        if ($parameter->isOptional()) {
            try {
                yield $parameter->getDefaultValue();
            } catch (\ReflectionException $e) {
                // Can't get default values from PHP internal classes and functions
            }
        }
    },
    
    TypeHintContainerResolver::class      => function (
        ReflectionParameter $parameter
    ) use ($container) {
        if (($class = $parameter->getClass()) && $container->has($class->name)) {
            yield $container->get($class->name);
        }
    },
    
    ParameterNameContainerResolver::class => function (
        ReflectionParameter $parameter
    ) use ($container) {
        if (($name = $parameter->name) && $container->has($name)) {
            yield $container->get($name);
        }
    },
    
];

$chain = new ResolverChain(array_map(function(callable $callback) {
    return new GeneratorResolver($callback);
}, $callbacks));

```

**Comment by mnapoli** [comment]
Thank you but this introduces too much complexity for use cases that aren't really obvious. Will put that aside for the moment.

**Pull request closed without merging**
